legends = {
  'All'                                                          : 'Every quality',
  'correlated'                                                   : 'Correlated Only',
  'legacy'                                                       : 'Legacy qualities',
  'index0'                                                       : 'Only Index 0',
  'index01'                                                      : 'Only Index 01',
  'index012'                                                     : 'Only Index 012',
  'index0123'                                                    : 'Only Index 0123',
  'nothreehits'                                                  : 'Quality > 2',
  'withmatchedthreehits'                                         : 'Quality > 2 + RPC-matched Quality<=2',
  'qualityORSegs'                                                : 'Every DT quality + RPC segments',
  'qualityORSegsClus'                                            : 'Every DT quality + RPC segments and clusters',
  'qualityMatchedORSegs'                                         : 'Quality > 2 + RPC-matched Quality<=2 + RPC segments',
  'qualityMatchedORSegsClus'                                     : 'Quality > 2 + RPC-matched Quality<=2 + RPC segments and clusters',
  'AM'                                                           : 'AM',
  'HB'                                                           : 'HB',
  'nu_pu250_noage_norpc'                                         : 'Nu gun PU250 + no bkg',  
  'nu_pu250_noage_norpcGoodBX'                                   : 'No random AllQ',  
  'nu_pu250_noage_norpcGoodBX+qu>=3'                             : 'No random Q>=3',  
  'nu_pu250_age_norpc_youngseg_muonage_norpcage_fail_3000'             : 'w/Aging No RPC',
  'nu_pu250_age_norpc_youngseg_muonage_norpcage_fail_3000GoodBX'       : 'No random w/Aging AllQ',
  'nu_pu250_age_norpc_youngseg_muonage_norpcage_fail_3000GoodBX+qu>=3' : 'No random w/Aging Q>=3',
  'nu_pu250_noage_withrpc'                                       : 'No Aging w/RPC',  
  'nu_pu250_age_withrpc_youngseg_muonage_norpcage_fail_3000'     : 'w/Aging w/RPC',  
  'PU0_bkgHits'                                                  : 'PU0 + bkg',  
  'PU200_bkgHits'                                                : 'PU200 + bkg',  
  'PU200_nu_bkg7p5'                                              : 'Nu gun PU200 + bkg7.5',  
  'PU250_nu_bkg9'                                                : 'Nu gun PU250 + bkg9',  
  'PU250_nu_bkg9GoodBX'                                          : 'Random 9E34 AllQ',  
  'PU250_nu_bkg9GoodBX+qu>=3'                                    : 'Random 9E34 Q>=3',  
  'nopu_noage_norpc'                                             : 'PU0 NoAging',  
  'pu200_noage_norpc'                                            : 'PU200 No Aging',
  'pu200_noage_withrpc'                                          : 'PU200 w/RPC',
  'mu_pu200'                                                     : 'PU 200 TDR',
  'mu_pu0'                                                       : 'PU0 No Aging',
  'mu_PU200_noRPC_withAgeing'                                    : 'PU 200 Aged',
  'mu_PU200_noRPC_noAgeing_grouping2'                            : 'PU 200 Grouping 2', 
  'mu_PU200_noRPC_noAgeing_dev'                                  : 'PU 200 1.0', 
  'mu_PU200_noRPC_noAgeing_111X_1_0'                             : 'PU 200 111X_1.0',
  'mu_PU200_noRPC_withAgeing_111X_1_0'                           : 'PU 200 111X_1.0 w/aging',
  'mu_PU200_noRPC_noAgeing_111Xdev'                              : 'PU 200 11XDev', 
  'mu_PU200_noRPC_noAgeing_last_int'                              : 'PU 200', 
  'mu_PU200_noRPC_noAgeing_newAnalyzer'                          : 'PU 200 new analyzer',
  'mu_PU200_noRPC_noAgeing_newAnalyzer_notuck'                   : 'PU 200 new analyzer w/o tuck',
  'DTDPGNtuple_11_1_0_patch2_Phase2_Simulation_8muInBarrel'      : 'PU 200 + real bkg w/RPC',
  'DTDPGNtuple_11_1_0_patch2_Phase2_Simulation_8muInBarrelGoodBX': 'PU 200 + real bkg w/RPC AllQ',
  'DTDPGNtuple_11_1_0_patch2_Phase2_Simulation_8muInBarrelGoodBX+qu>=3': 'PU 200 + real bkg w/RPC Q>=3',
  'DTDPGNtuple_11_1_0_patch2_Phase2_Simulation_8muInBarrel_woRPC'      : 'PU 200 + real bkg',
  'DTDPGNtuple_11_1_0_patch2_Phase2_Simulation_8muInBarrel_woRPCGoodBX': 'PU 200 + real bkg AllQ',
  'DTDPGNtuple_11_1_0_patch2_Phase2_Simulation_8muInBarrel_woRPCGoodBX+qu>=3': 'PU 200 + real bkg Q>=3',
}
